import { build } from "esbuild";
import { writeFile } from "node:fs/promises";
const result = await build({
  entryPoints: ["server/worker.ts"],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node22",
  write: false,
  minify: true,
});
await writeFile(
  "shared/worker-source.ts",
  `// Generated by npm run prepare.\nexport const workerSource = ${JSON.stringify(result.outputFiles[0].text)};\n`,
);
